---
# tasks file for ntp

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
  tags:
    - vars
    - install

- name: Test curl installed by package manager
  action: >
    {{ ansible_pkg_mgr }} name=curl state=present
  register: package_result
  failed_when: package_result.msg is defined and package_result.msg == "No package matching 'curl' is available"
  tags:
    - install

- name: Test path to curl exists
  shell: which curl
  register: which_result
  failed_when: False
  tags:
    - install

- name: Fail if curl not installed
  fail: msg="curl is not installed on the machine."
  when: package_result.msg is defined and package_result.msg == "No package matching 'curl' is available" and which_result.rc != 0
  tags:
    - install

- set_fact: curl_path=which_result.stdout
  tags:
    - install

- name: sync time with hardware clock
  shell: hwclock -s
  ignore_errors: yes
  failed_when: False
  tags:
    - time

- name: set local time manually from remote server as backup
  shell: >
    date -s "$(curl -s --head http://google.com | grep ^Date: | sed 's/Date: //g')"
  ignore_errors: yes
  failed_when: False
  tags:
    - time

- name: install ntp prep package(s) -- Ubuntu only
  shell: >
    apt-get -qy install {{ NTP_PREP_PACKAGE.name }}
  tags:
    - install
  when: ansible_distribution == "Ubuntu" and NTP_PREP_PACKAGE is defined and NTP_PREP_PACKAGE.name != ""

- name: install ntp prep package(s) -- Non-Ubuntu using action module
  action: >
    {{ ansible_pkg_mgr }} name={{ NTP_PREP_PACKAGE.name }} state={{ NTP_PREP_PACKAGE.state }}
  tags:
    - install
  when: ansible_distribution != "Ubuntu" and NTP_PREP_PACKAGE is defined and NTP_PREP_PACKAGE != ""

- name: install ntp package
  action: >
    {{ ansible_pkg_mgr }} name={{ NTP_PACKAGE.name }} state={{ NTP_PACKAGE.state }}
  tags:
    - install

- name: stop ntp service
  action: >
    service name={{ NTP_SERVICE }} state=stopped

- name: verify that ntp is installed
  stat: path=/etc/ntp.conf
  register: ntp_installed

- name: update system date manually
  shell: ntpdate 1.us.pool.ntp.org
  when: ntp_installed.stat.exists == False
  tags:
    - time

# Only run if on a hardware system. i.e. non-vm
#- name: update hardware clock manually
#  shell: hwclock --systohc
#  when: ntp_installed.stat.exists == False

- name: configure ntp
  template: src={{ item }} dest={{ NTP_CONFIG }}
  with_first_found:
    - "../templates/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.ntp.conf.j2"
    - "../templates/{{ ansible_distribution }}.ntp.conf.j2"
    - "../templates/{{ ansible_os_family }}.ntp.conf.j2"
  tags:
    - template
  when: SET_NTP_SERVERS == true

- name: 'Place CentOS ntp.sh (dhclient.d script) which removes pre-existing NTP servers from ntp.conf when setting DHCP-provided NTP servers'
  template:
    src: '{{ item }}'
    dest: '/etc/dhcp/dhclient.d/ntp.sh'
    owner: 'root'
    mode: 'u=rwx,g=rx,o=rx'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.ntp.sh.j2'
  when: 'ansible_distribution == "CentOS"'

- name: 'Renew DHCP lease for CentOS'
  command: 'dhclient'
  when: 'ansible_distribution == "CentOS"'

- name: start ntp service
  action: >
    service name={{ NTP_SERVICE }} state=restarted enabled=yes
